comment: Config for MLP from https://eprint.iacr.org/2017/396.pdf

ckks_params:
  LogN: 13
  LogQ: [29, 26, 26, 26, 26, 26]
  LogP: [29, 29]
  LogScale: 26
  H: 8192
  RingType: ConjugateInvariant

orion:
  margin: 2
  embedding_method: hybrid
  backend: lattigo
  fuse_modules: true
  debug: false
  diags_path: ../data/diagonals.h5
  keys_path: ../data/keys.h5
  io_mode: none
